name: very_good_flame_game_hooks

environment:
  sdk: ^3.10.0

dependencies:
  clock: ^1.1.1
  equatable: ^2.0.5
  mason: ^0.1.0
  meta: ^1.16.0
  very_good_core_hooks:
    git:
      path: very_good_core/hooks
      ref: 5d7f3848b432296f02aa3728883adf2e75615b3a
      url: https://github.com/VeryGoodOpenSource/very_good_templates

dev_dependencies:
  mocktail: ^1.0.3
  test: ">=1.25.2 <1.27.0"
  very_good_analysis: ^10.1.0
