name: {{project_name.snakeCase()}}_android
description: Android implementation of the {{project_name.snakeCase()}} plugin
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: {{{dartSdkVersionBounds}}}

flutter:
  plugin:
    implements: {{project_name.snakeCase()}}
    platforms:
      android:
        package: {{org_name.dotCase()}}
        pluginClass: {{project_name.pascalCase()}}Plugin
        dartPluginClass: {{project_name.pascalCase()}}Android

dependencies:
  flutter:
    sdk: flutter
  {{project_name.snakeCase()}}_platform_interface:
    path: ../{{project_name.snakeCase()}}_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0{{#use_build_hooks}}
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.0{{/use_build_hooks}}
