version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/very_good_core/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/very_good_dart_cli/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/very_good_wear_app/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/very_good_wear_app/e2e"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/very_good_flutter_plugin/hooks"
    schedule:
      interval: "daily"
