name: merge_coverage
description: Merge coverage reports from multiple packages into a single report.

environment:
  sdk: ^3.8.0

dependencies:
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  very_good_analysis: ^9.0.0
