name: dependency_tightener
description: Ensures all the packages in the directory have tight dependencies.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  pub_semver: ^2.1.4
  pub_updater: ^0.4.0
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^7.0.0

executables:
  dependency_tightener:
