name: {{project_name.snakeCase()}}_example
description: Demonstrates how to use the {{project_name.snakeCase()}} plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: {{{dartSdkVersionBounds}}}

dependencies:
  flutter:
    sdk: flutter
  {{project_name.snakeCase()}}:
    # When depending on this package from a real application you should use:
    #   {{project_name.snakeCase()}}: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.1.0-rc.1

flutter:
  uses-material-design: true
