name: {{project_name.snakeCase()}}
description: {{description}}
version: 0.0.1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0

executables:
  {{executable_name.snakeCase()}}:
