name: {{project_name.snakeCase()}}
description: {{description}}
version: 0.0.1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  mason_logger: ^0.2.12
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0

executables:
  {{executable_name.snakeCase()}}:
