name: {{project_name.snakeCase()}}
description: {{description}}
version: 0.0.1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.10.3
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.27.0
  very_good_analysis: ^10.1.0

executables:
  {{executable_name.snakeCase()}}:
