name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.6.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
