name: very_good_flutter_plugin_hooks

environment:
  sdk: ^3.10.0

dependencies:
  mason: ^0.1.0
  meta: ^1.12.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ">=1.25.2 <1.27.0"
  very_good_analysis: ^10.0.0
