name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  equatable: ^2.0.7
  flame: ^1.22.0
  flame_audio: ^2.10.6
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flame_test: ^1.17.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.6.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
