name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.10.0
{{#use_build_hooks}}

dependencies:
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.0
{{/use_build_hooks}}

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.0.0
