name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 0.1.0+1
{{^publishable}}publish_to: none{{/publishable}}

environment:
  sdk: ^3.10.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.27.0
  very_good_analysis: ^10.1.0-rc.1
