name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.2.0
  equatable: ^2.0.8
  flame: ^1.35.1
  flame_audio: ^2.11.14
  flame_behaviors: ^1.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.0.1
  intl: ^0.20.2

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.22
  flame_test: ^2.2.2
  flutter_test:
    sdk: flutter
  mockingjay: ^2.1.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
