name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.1.0
  equatable: ^2.0.7
  flame: ^1.33.0
  flame_audio: ^2.11.11
  flame_behaviors: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  bloc_lint: ^0.3.3
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flame_test: ^2.1.0
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
