name: very_good_flutter_package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/very_good_flutter_package.yaml
      - "very_good_flutter_package/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/very_good_flutter_package.yaml
      - "very_good_flutter_package/**"
    branches:
      - main

jobs:
  brick:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v5

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - name: ğŸ§± Mason Make
        run: |
          dart pub global activate mason_cli
          mason get
          mason make very_good_flutter_package -c very_good_flutter_package/config.json --on-conflict overwrite -o very_good_flutter_package_output

      - name: ğŸ“¦ Install Dependencies
        run: |
          dart pub global activate very_good_cli
          very_good packages get --recursive very_good_flutter_package_output

      - name: âœ¨ Check Formatting
        run: dart format --set-exit-if-changed very_good_flutter_package_output

      - name: ğŸ•µï¸ Analyze
        run: dart analyze --fatal-infos --fatal-warnings very_good_flutter_package_output

      - name: ğŸ§ª Run Tests
        run: |
          cd very_good_flutter_package_output
          very_good test -j 4 --recursive --optimization --coverage --test-randomize-ordering-seed random

      - name: ğŸ“Š Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          path: very_good_flutter_package_output/coverage/lcov.info
